import RPi.GPIO as GPIO
import time

#Initialize
GPIO.setmode(GPIO.BOARD)
GPIO.setup(12, GPIO.OUT)

def doot():
    GPIO.output(12, GPIO.HIGH) #dut5
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(1.2) #delay
    GPIO.output(12, GPIO.HIGH) #DUUUUT
    time.sleep(0.25)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.25) #delay
    GPIO.output(12, GPIO.HIGH) #dut5
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(1.2)
    GPIO.output(12, GPIO.HIGH) #dut5 1
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(1.2)
    GPIO.output(12, GPIO.HIGH) #dut5 2
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(1.2)
    '''
    GPIO.output(12, GPIO.HIGH) #dut5 3
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(1.2)
    GPIO.output(12, GPIO.HIGH) #dut5 4
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(1.2)
    '''
    GPIO.output(12, GPIO.HIGH) #dut5 2.1
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.42) #del
    GPIO.output(12, GPIO.HIGH) #dut5 2.2
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.42) #del
    GPIO.output(12, GPIO.HIGH) #dut5 2.3
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.42) #del
    GPIO.output(12, GPIO.HIGH) #dut5 2.4
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.42) #del
    GPIO.output(12, GPIO.HIGH) #dut5 3.1
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05) #del
    GPIO.output(12, GPIO.HIGH) #dut5 3.2
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05) #del
    GPIO.output(12, GPIO.HIGH) #dut5 3.3
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05) #del
    GPIO.output(12, GPIO.HIGH) #dut5 3.4
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05) #del
    GPIO.output(12, GPIO.HIGH) #dut5 3.5
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05) #del
    GPIO.output(12, GPIO.HIGH) #dut5 3.6
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05) #del BOOm!

doot()
